title: "Cameron Ayre"
description: "Some useful Power BI things :)" 

theme: "minima"
    
plugins:
  - jekyll-feed
  - jekyll-sitemap

titles_from_headings:
  strip_title: true
  collections: true

defaults:
  - scope:
      path: ""
      type: post
    values:
      tags: Other
