title: "Cameron Ayre"
description: "Some useful Power BI things :)" 

remote_theme: pages-themes/cayman@v0.2.0

kramdown:
  syntax_highlighter_opts:
    disable: true
    
plugins:
  - jekyll-feed
  - jekyll-sitemap
  - jekyll-remote-theme

titles_from_headings:
  strip_title: true
  collections: true

defaults:
  - scope:
      path: ""
      type: post
    values:
      tags: Other
